name: server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  meta: ^1.3.0
  socket_io: ^0.9.4
  common:
    path: ../common
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
